### ISSUE TITLE
Prevent sending the same answer multiple times

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-android#113]
Currently the answer to a question is saved every time the user moves to another question or exits the question screen. Even if the same answer was already sent. Find a way to not resend the answer if it hasn't changed.

**Comment by bvizureanu** [comment]
alter the `question` model and include a flag that can save the "sent to server" state.

on attempt to send the answers to server - filter on this flag and only send the data that was not already sent.

If changing an answer to a question - reset the flag (the question will then be sent to the server - regardless if the answer is exactly the same as before; the user attempted a change - that is enough to reset the flag and resend to server)

persist the answer locally on change
send the data to server when leaving the question enumerator (either by going back to the sections/forms or by switching the state of the application - for example `onPause()` )

**Comment by RaduCStefanescu** [comment]
In progress @ Damian Robert Andrei
