### ISSUE TITLE
API 28 HTTP clear text not permitted

### ISSUE THREAD

**Issue by marian-eremia** [code4romania/monitorizare-vot-android#122]
The "Guide" section does not load due to http clear text url loaded in webview.

"Starting with Android 9.0 (API level 28), cleartext support is disabled by default."
https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted

![image](https://user-images.githubusercontent.com/1318132/55275191-2c90f380-52eb-11e9-89c0-d901739bfbfe.png)

**Comment by RaduCStefanescu** [comment]
In progress @marian-eremia
