### ISSUE TITLE
Remove hardcoded form names and description from forms list

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-android#127]
Currently the form names and short descriptions for them are hardcoded in the app:

```
<!-- Forms list -->
    <string name="form_1">Saturday Form</string>
    <string name="form_1_letter">SA</string>
    <string name="form_2">Sunday Form</string>
    <string name="form_2_letter">SU</string>
    <string name="form_3">Counting Form</string>
    <string name="form_3_letter">C</string>
```

Please use the info retrieved from the call to GET /api/v1/formular

```
"codSectiune": "A"
"descriere": "Deschidere"
```

![Screenshot_20190401-155217_Monitorizare Vot](https://user-images.githubusercontent.com/1358055/55329028-4e7aa980-5496-11e9-8bdb-cd1edccf0faa.jpg)

**Comment by RaduCStefanescu** [comment]
I think this relates to: https://github.com/code4romania/monitorizare-vot-votanti-api/issues/24

**Comment by aniri** [comment]
we should also display the form versions somewhere https://github.com/code4romania/monitorizare-vot-android/issues/77
