### ISSUE TITLE
Remove hardcoded info for counties

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-android#139]
A new endpoint was created to retrieve the counties data from the API. Call it and use the returned results instead of the current hardcoded counties enum.

The call should be made after login and the results should be persisted in local db.

A small enhancement is still needed from backend for this to be complete: https://github.com/code4romania/monitorizare-vot/issues/117

**Comment by damianr13** [comment]
Solved and submitted pull request: #141
