### ISSUE TITLE
Don't silence errors in SyncAdapter

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-android#43]

**Comment by KrzysztofMadejski** [comment]
Printing stack trace is great comparing to fully silencing like in #68 causing "No data set for forms"

**Comment by KrzysztofMadejski** [comment]
When observer sends a report and polling station is not existing in the db this is not reported to the user. (maybe shouldn't be -> maybe data upload status #46 will be enough). 

On API side that is mentioned as:
```
fail: VotingIrregularities.Api.Services.SectieDevotareDBService[0]
mv-api    |       Sectie inexistenta pentru: { idJudet = 146507, numarSectie = 1 }
```
Results in 404 error from the API.

**Comment by RaduCStefanescu** [comment]
These kind of errors should not appear in the new version of the app.
All information, including the number of polling stations are pulled from backend.
Issue added in features of new version of the app.
