### ISSUE TITLE
Set end observation time when changing polling station

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-android#45]
When I change polling station app should ask me to set end observation time first. Now I don't see how it is possible to set this value.
It would be even better if there was a button / menu item for doing that as "Change polling station" is not the most intuitive if someone is not changing it. :)

**Comment by KrzysztofMadejski** [comment]
Current way to do it:
- click "change polling station"
- choose the same that you are in
- set end time
- confirm
- click "change polling station" to choose a new one

**Comment by RaduCStefanescu** [comment]
Issue added in features of new version of the app.
