### ISSUE TITLE
Multiple language versions of forms

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-android#49]
Use case: We will have a lot of local observers, but also some international ones. It would be great to offer international ones the same questions, but in their language. 

It would require:
- [ ] API storing many labels and answers (for each language)
- [ ] pull from API necessary language
- [ ] tag responses with language code to be able to filter through it
- [ ] reload forms if system language changes

It could be realized in a non-breaking API way by sending `Accept-Language` headers on `getForm`.

**Comment by RaduCStefanescu** [comment]
Issue added in features of new version of the app.
