### ISSUE TITLE
Dynamic number of forms 

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-android#50]
So we don't stick to A,B,C, but can make more.

Use case: C form (vote counting) has two phases: first pass and then a second commission doing control. We are thinking to divide that in two. It's not a necessity, more like nice to have.

**Comment by KrzysztofMadejski** [comment]
For now I'm hard-coding it into Polish version.

**Comment by KrzysztofMadejski** [comment]
@bvizureanu I was working on this. The backend is done - one can add multiple forms, but I'm struggling with layout.

I've tried to add `GridLayout`, but I couldn't populate it dynamically. What is missing:
- [ ] Create GridLayout here https://github.com/epforgpl/monitorizare-vot-android/compare/master...epforgpl:feature_50/multiple_forms#diff-d5e39bd06cf8895b475ee504621fa985R23 
- [ ] Populate it from code here: https://github.com/epforgpl/monitorizare-vot-android/compare/master...epforgpl:feature_50/multiple_forms#diff-90b65d3bd416f0b5e294f6ab9a546324R31

**Comment by KrzysztofMadejski** [comment]
Final form names:

A: Przygotowanie
B: Głosowanie
C1: Przekazanie
C2: Liczenie - ogólne
Cg: Liczenie - gmina
Cp: Liczenie - powiat
Cs: Liczenie - sejmik
Cw: Liczenie - wójt
D: Tabulacja

**Comment by aniri** [comment]
closing as it was solved in https://github.com/code4romania/monitorizare-vot-android/issues/120
