### ISSUE TITLE
New question types

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-android#54]
- [ ] provide time
- [ ] provide number
- [ ] +1 (used to count voters seen or other ongoing counting)

They should have validation and easy to enter value.

The workaround now is to create question with one option of type `Single with text` and free text set to on. Option could be named `Click and enter answer` so they now they have to click it.

Propagate it to API, iOS and other repos.

**Comment by RaduCStefanescu** [comment]
This one is fixed in the newer versions.
