### ISSUE TITLE
Section don't have unique identifiers

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-android#55]
`Section.java` doesn't store in realm section.Id, so when multiple sections have the same Code the questions in the interface are getting mixed up. API is not serving this id, see https://github.com/code4romania/monitorizare-vot/issues/72

Android uses `code/codSectiune` as `@PrimaryKey`.
Database uses id as a PrimaryKey:
```
create table FormSections
(
	Id int not null
		constraint PK_FormSection
			primary key,
	Code nvarchar(4) not null,
	Description nvarchar(200) not null
```

**Comment by RaduCStefanescu** [comment]
This one is fixed in https://github.com/code4romania/monitorizare-vot-android/pull/138
