### ISSUE TITLE
Demo application

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-android#63]
Acceptance criteria:
- [x] looking fabulous (adapted to local context)
- [x] mocked API so anyone can test it without the need of the DB
- [x] pushed to Google Store
- [x] make it a demo [build flavor](https://developer.android.com/studio/build/build-variants)
- [ ] make English demo with OSCE forms that could be used by anyone globally to test the app
- [ ] warn that's a demo while sending answers
- [ ] put some fake telephone and code so ppl won't think what to put there

**Comment by KrzysztofMadejski** [comment]
https://developer.android.com/studio/build/build-variants

**Comment by KrzysztofMadejski** [comment]
Observation: many ppl didn't understand the difference between DEMO and non-DEMO version. 
- [ ] It would be good to show a splash anytime the data should go to the server saying : "This is a DEMO version. Data is NOT sent to the observation center".

**Comment by RaduCStefanescu** [comment]
Issue added in features of new version of the app.
