### ISSUE TITLE
Replace mediapicker library

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-android#64]
The currently used mediapicker library raises some security concerns on newer phones. A hot-fix was made to prevent any crashes. 

The library should be replaced with a newer one or we could use native file browser and camera.

**Comment by KrzysztofMadejski** [comment]
+1 for native support

czw., 4 paź 2018, 18:37 użytkownik Irina <notifications@github.com> napisał:

**Comment by KrzysztofMadejski** [comment]
Resolved in https://github.com/epforgpl/monitorizare-vot-android/pull/4 by introducing native file browser.
