### ISSUE TITLE
UID cannot explicitly add accounts of type: code4.ro

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-android#71]
Error shown on one person device after the login.
Login details: number (without prefix) and pass 00000
System: Android 6.0.1

![43952635_10156159984318423_509840990589157376_n](https://user-images.githubusercontent.com/849975/46929350-cc153f00-d047-11e8-8104-251058579c79.jpg)

After that when a person wants to starts the app it hangs.

![43952839_10156159985998423_8082041957490098176_n](https://user-images.githubusercontent.com/849975/46929362-de8f7880-d047-11e8-8b82-8478bbbb90c3.jpg)

**Comment by bvizureanu** [comment]
cannot reproduce
