### ISSUE TITLE
Schimbare control la alegere sectie

### ISSUE THREAD

**Issue by bvizureanu** [code4romania/monitorizare-vot-android#9]
Control-ul care face alegerea sectiei curente va fi transformat intr-un input box de tip numeric.
Fiecarui judet i se va adauga un camp ce va seminifica maximul sectiilor de votare din acel judet.
Maximul numarului de sectii va deveni regula de validare a input-ului (1 <= Sectie <= MaxNrSectii)

**Comment by tudormarze** [comment]
Done
