### ISSUE TITLE
Code peer review

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-android#90]
Thank you @tajchert for that!

- There are no tests!! 
- would be cleaner to use kotlin instead of java
  - should cut 20% of the code at least because of getting rid of getters and setters
- you could use dependency injection (if java then DI such as koin/dagger)
- even if the database is small Realm adds +5MB to the app size; I'd suggest throwing away local database and use Room by Google - https://developer.android.com/topic/libraries/architecture/room
- the number of custom views susch as [this](https://github.com/code4romania/monitorizare-vot-android/blob/master/app/src/main/java/ro/code4/monitorizarevot/widget/AnswerCheckbox.java) seems like an overkill
- I'd throw away Hockey App unless someone has a very good reason to use it
- there is only one presenter - is there really so little logic? I'd investigate it

**Comment by bvizureanu** [comment]
Thank you so much for the suggestions
@aniri, @tudormarze, I think there is a lot of value in these upgrades; can you review?

**Comment by aniri** [comment]
Wow, yeah, thanks @KrzysztofMadejski for the list! We really have to do a major cleanup of the apps. I think you included all the problems I found as well. I'd keep hockey or add crashlytics for tracking the crashes. @bvizureanu I think we could also use an UX review and then we could move on and make the improved app version!

**Comment by RaduCStefanescu** [comment]
Great suggestions @KrzysztofMadejski 
Saved and added to features of new app planning document.
